### ISSUE TITLE
cf uninstall-plugin [name] runs the plugin before actually uninstalling

### ISSUE THREAD

**Issue by aeckard87** [cloudfoundry/cli-plugin-repo#195]
cf version 6.33.1+c77e55743.2017-12-15 on a unix (mac) machine

While developing a plugin - I noticed during a plugin uninstall the plugin will actually run before uninstalling. I tried this against other established plugins and found the same result. 

This doesn't seem like a wanted result for the uninstall process. 

Let me know if you need any more details.

**Comment by nickwei84** [comment]
Hi @aeckard87. This is by design. It provides a hook for plugin developers to do custom cleanup before the CLI removes the plugin binary. What's happening when you run `cf uninstall-plugin your-plugin-name` is that it calls your plugin binary with "CLI-MESSAGE-UNINSTALL" as the command line argument before it deletes the plugin binary and removes it from the plugin registry.  FYI, if you don't have custom cleanup, you still need to explicitly handle this call to your plugin binary. This is documented [here](https://github.com/cloudfoundry/cli/tree/master/plugin/plugin_examples#uninstalling-a-plugin), but the information is basically what I described.

**Comment by aeckard87** [comment]
awesome! I glazed right over this, thanks. Got it working as expected now.
